# Generated by Django 3.2.1 on 2023-11-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
            options={
                'db_table': 'tipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('apellido', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('tipoUsuario', models.CharField(default='DEFAULT VALUE', max_length=60)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
